environment: test

env:
  HOST: 0.0.0.0
  PORT: "1337"
  NODE_ENV: test
  DATABASE_CLIENT: postgres
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  DATABASE_SSL: "false"
  S3_ENDPOINT: http://minio:9000

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

