environment: prod

replicaCount: 2

image:
  repository: "<OCIR_REGISTRY>/<OCIR_NAMESPACE>/almadar-strapi"
  tag: latest
  pullPolicy: IfNotPresent

workingDir: /opt/app

command:
  - npm
  - run
  - start

env:
  HOST: 0.0.0.0
  PORT: "1337"
  NODE_ENV: production
  DATABASE_CLIENT: postgres
  DATABASE_HOST: "<OCI_POSTGRES_PRIVATE_IP_OR_DNS>"
  DATABASE_PORT: "5432"
  DATABASE_SSL: "true"
  S3_ENDPOINT: ""

args: []

migrations:
  enabled: true

initContainers:
  postgres:
    host: "<OCI_POSTGRES_PRIVATE_IP_OR_DNS>"
  minio:
    enabled: false

volumes:
  source:
    enabled: false
    type: hostPath
    mountPath: /workspace/apps/strapi
    hostPath: /workspace/almadar-platform/apps/strapi
  nodeModules:
    enabled: false
    mountPath: /workspace/apps/strapi/node_modules

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: "2"
    memory: 2Gi
