environment: prod

replicaCount: 2

service:
  type: ClusterIP

env:
  CANTALOUPE_S3SOURCE_ENDPOINT: ""

resources:
  requests:
    cpu: 250m
    memory: 768Mi
  limits:
    cpu: "1"
    memory: 1536Mi

persistence:
  size: 10Gi
