apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: oci-vault
spec:
  provider:
    oracle:
      vault: "<OCI_VAULT_OCID>"
      region: "<OCI_REGION>"
      principalType: Workload
      serviceAccountRef:
        namespace: external-secrets
        name: external-secrets
