apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: almadar-secrets
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault
  target:
    name: almadar-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: almadar-dev-postgres
    - extract:
        key: almadar-dev-jwt
    - extract:
        key: almadar-dev-strapi
    - extract:
        key: almadar-dev-s3
