apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: almadar-secrets
  namespace: test
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault
  target:
    name: almadar-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: almadar-test-postgres
    - extract:
        key: almadar-test-jwt
    - extract:
        key: almadar-test-strapi
    - extract:
        key: almadar-test-s3
