apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cluster-secret-store.yaml
  - externalsecret-dev.yaml
  - externalsecret-test.yaml
  - externalsecret-prod.yaml
