variable "kubeconfig_path" {
  description = "Path to kubeconfig generated by the OKE Terraform stack."
  type        = string
  default     = "../oke/generated/oke-kubeconfig.yaml"
}

variable "kubeconfig_context" {
  description = "Optional kubeconfig context name. Leave null to use the current context in the generated kubeconfig."
  type        = string
  default     = null
}

variable "namespaces" {
  description = "Kubernetes namespaces to create."
  type        = set(string)
  default     = ["dev", "test", "prod"]
}

variable "deployer_service_account_name" {
  description = "ServiceAccount created in each namespace for CI/CD deployments."
  type        = string
  default     = "deployer"
}
